## Clock signal (100MHz on Basys3)
set_property PACKAGE_PIN W5 [get_ports clk]							
set_property IOSTANDARD LVCMOS33 [get_ports clk]
create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk]

## Buttons
set_property PACKAGE_PIN U18 [get_ports btnC]						
set_property IOSTANDARD LVCMOS33 [get_ports btnC]
set_property PACKAGE_PIN T18 [get_ports btnU]						
set_property IOSTANDARD LVCMOS33 [get_ports btnU]
set_property PACKAGE_PIN U17 [get_ports btnD]						
set_property IOSTANDARD LVCMOS33 [get_ports btnD]
set_property PACKAGE_PIN T17 [get_ports btnR]						
set_property IOSTANDARD LVCMOS33 [get_ports btnR]

## Status LEDs
set_property PACKAGE_PIN N3  [get_ports led_busy]					
set_property IOSTANDARD LVCMOS33 [get_ports led_busy]
set_property PACKAGE_PIN P1  [get_ports led_fault]					
set_property IOSTANDARD LVCMOS33 [get_ports led_fault]
set_property PACKAGE_PIN L1  [get_ports led_done]					
set_property IOSTANDARD LVCMOS33 [get_ports led_done]

## Data LEDs (LD0..LD7)
set_property PACKAGE_PIN U16 [get_ports {led_data[0]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {led_data[0]}]
set_property PACKAGE_PIN E19 [get_ports {led_data[1]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {led_data[1]}]
set_property PACKAGE_PIN U19 [get_ports {led_data[2]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {led_data[2]}]
set_property PACKAGE_PIN V19 [get_ports {led_data[3]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {led_data[3]}]
set_property PACKAGE_PIN W18 [get_ports {led_data[4]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {led_data[4]}]
set_property PACKAGE_PIN U15 [get_ports {led_data[5]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {led_data[5]}]
set_property PACKAGE_PIN U14 [get_ports {led_data[6]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {led_data[6]}]
set_property PACKAGE_PIN V14 [get_ports {led_data[7]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {led_data[7]}]
